#ifndef __GO4_FOOT_UNPACK_COMMON_HH__
#define __GO4_FOOT_UNPACK_COMMON_HH__

#define MAX_FOOT_I 32

#define FOOT_RAW_DATA_WORDS 320 
#define FOOT_CHN (2 * FOOT_RAW_DATA_WORDS)

#define UNPACK_FOOT_WR_SUBEV



#endif /* __GO4_FOOT_UNPACK_COMMON_HH__ */
